# The Numpy random package
### Carlos Montes   -   November 2018

## 1) Simple random data

In [11]:
# First of all we need to import the package. We also rename it as np to ease its use
import numpy as np

### 1.1) rand
We can generate a single float between 0 and 1, being 1 excluded [0,1), by leaving out the arguments. With all this commands, whenever we don't pass arguments we get one single value.

In [23]:
np.random.rand()

0.4930957133063524

In [24]:
# We can also get an array with random values from a uniform distribution. The numbers within the parentheses shape the array.
# The first one specifies the numbers of arrays within the array, the second shows the number of values within each array
np.random.rand(4,3)
# The result is an n-dimensional array, an array of arrays, which is a 2 dimensional array. The first argument, number 4, 
# represents the number of subarrays within the array whereas the second argument -3- shows the number of elements within 
# every subarray. 

array([[0.47891784, 0.57823257, 0.51450413],
       [0.72957918, 0.02396064, 0.71783672],
       [0.52313278, 0.19589111, 0.25651549],
       [0.20451557, 0.73012195, 0.67137668]])

In [20]:
# if we add a third parameter
np.random.rand(4,3,2)
# we get a 3-dimensional array where the subarrays are made up of 2 elements each

array([[[0.72077198, 0.04563786],
        [0.22134135, 0.51896203],
        [0.49832183, 0.86433184]],

       [[0.73943143, 0.16555873],
        [0.45781062, 0.31412087],
        [0.80461189, 0.60365558]],

       [[0.19316201, 0.66835105],
        [0.46497217, 0.49785591],
        [0.34157661, 0.86717195]],

       [[0.99542084, 0.62699626],
        [0.2613822 , 0.49364669],
        [0.96089357, 0.01250429]]])

### 1.2) randn
This command generates an array of data with the same shape as the one explained above but in this case we can specify the median around which we want the samples to be. Also the variance can be an input, the greater it is the bigger the dispersion of the sample in relation to the mean. This is a univariative normal disribution also known as Gauss distribution which has typical bell-like shape.

variance * np.random.randn(...) + median

In [34]:
0.5 * np.random.randn(3,2) + 6
# All the samples outputed are relatively near the median, 6

array([[6.11517539, 5.90274274],
       [5.75917424, 6.02703061],
       [6.34236494, 6.1981922 ]])

In [35]:
3 * np.random.randn(3,2) + 6
# All the samples outputed are further to the median because the variance is greater

array([[ 2.14751811, 10.06035613],
       [ 3.18798053,  5.30838364],
       [ 9.64975214,  6.37724051]])

In [67]:
x = np.random.standard_normal(3000)
x.shape

(3000,)

In [69]:
y = np.random.standard_normal(size=(7, 3, 5))
y.shape

(7, 3, 5)